<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import SitterPageShell from '../components/sitter/SitterPageShell.vue'
import SitterDemoNotice from '../components/sitter/SitterDemoNotice.vue'
import { getSitterBooking, updateBookingStatus, type BookingPet, type SitterBooking } from '../services/sitterBookings'
const route=useRoute(), router=useRouter(), booking=ref<SitterBooking|null>(null), error=ref(''), confirmReject=ref(false), ownerOpen=ref(false), pet=ref<BookingPet|null>(null), busy=ref(false)
const canComplete=computed(()=>booking.value?.status==='in_service' && new Date(`${booking.value.endDate}T${booking.value.endTime}+07:00`)<=new Date())
async function load(){try{booking.value=await getSitterBooking(String(route.params.id))}catch(e){error.value=e instanceof Error?e.message:'Unable to load booking'}}
async function change(status:'waiting_service'|'cancelled'|'success'){if(!booking.value)return;busy.value=true;try{booking.value=await updateBookingStatus(booking.value.id,status);confirmReject.value=false}catch(e){error.value=e instanceof Error?e.message:'Unable to update booking'}finally{busy.value=false}}
onMounted(load)
</script>
<template><SitterPageShell><main class="page"><SitterDemoNotice /><button class="back" @click="router.push('/sitter/bookings')">‹ Back</button><p v-if="error" class="error">{{error}}</p><article v-if="booking" class="card"><div class="title"><div><h1>{{booking.owner.name}}</h1><span>{{booking.status.replaceAll('_',' ')}}</span></div><button v-if="booking.status==='waiting_confirm'" :disabled="busy" @click="change('waiting_service')">Confirm booking</button><button v-else-if="booking.status==='in_service'" :disabled="busy || !canComplete" @click="change('success')">Success</button></div>
<section><p class="label">Pet Owner Name</p><b>{{booking.owner.name}}</b><button class="link" @click="ownerOpen=true">View Profile</button></section><p class="label">Pet(s)</p><div class="pets"><button v-for="p in booking.pets" :key="p.id" class="pet" @click="pet=p"><img :src="p.avatarUrl||'/icon/paw.svg'" alt=""/><b>{{p.name}}</b><small>{{p.breed}}</small></button></div>
<div class="facts"><p><span>Duration</span>{{booking.duration}} {{booking.durationUnit}}</p><p><span>Booking Date</span>{{booking.startDate}} · {{booking.startTime.slice(0,5)}}–{{booking.endTime.slice(0,5)}}</p><p><span>Total Paid</span>฿{{booking.totalPrice.toLocaleString()}}</p><p><span>Transaction No.</span>{{booking.transactionNo||'—'}}</p><p><span>Additional Message</span>{{booking.additionalMessage||'—'}}</p></div><button v-if="booking.status==='waiting_confirm'" class="reject" @click="confirmReject=true">Reject Booking</button></article>
<div v-if="confirmReject" class="overlay"><div class="modal"><h2>Reject Confirmation</h2><p>Are you sure you want to reject?</p><button class="secondary" @click="confirmReject=false">Cancel</button><button @click="change('cancelled')">Reject Booking</button></div></div>
<div v-if="ownerOpen && booking" class="overlay" @click.self="ownerOpen=false"><div class="modal"><button class="close" @click="ownerOpen=false">×</button><img class="avatar" :src="booking.owner.avatarUrl||'/icon/user.svg'" alt=""/><h2>{{booking.owner.name}}</h2><p>{{booking.owner.email}}</p><p>{{booking.owner.phone}}</p></div></div>
<div v-if="pet" class="overlay" @click.self="pet=null"><div class="modal"><button class="close" @click="pet=null">×</button><img class="avatar" :src="pet.avatarUrl||'/icon/paw.svg'" alt=""/><h2>{{pet.name}}</h2><p>{{pet.breed}} · {{pet.sex}}</p><p>{{pet.ageMonths}} months · {{pet.weightKg}} kg</p><p>{{pet.about}}</p></div></div>
</main></SitterPageShell></template>
<style scoped>
.page{padding:32px;background:#f7f8fc;min-height:calc(100svh - 78px)}.back,.link{border:0;background:none;color:#ff7037}.card{max-width:980px;background:#fff;padding:32px;border-radius:12px}.title{display:flex;justify-content:space-between}.title h1{margin:0}.title span{color:#22c07f}.title button,.modal button:not(.close){border:0;border-radius:999px;background:#ff7037;color:#fff;padding:11px 20px}.label,.facts span{display:block;color:#9298ab;font-size:13px}.link{float:right}.pets{display:flex;gap:14px}.pet{display:grid;border:1px solid #e5e7f0;border-radius:8px;background:#fff;padding:12px}.pet img,.avatar{width:72px;height:72px;border-radius:50%;object-fit:cover;margin:auto}.facts{margin-top:24px}.facts p{line-height:1.7}.reject{float:right;border:0;background:none;color:#ff7037}.overlay{position:fixed;inset:0;background:#0009;display:grid;place-items:center;padding:20px;z-index:10}.modal{position:relative;background:#fff;border-radius:12px;padding:28px;min-width:min(100%,340px);text-align:center}.modal .secondary{background:#fff!important;color:#ff7037!important;border:1px solid #ff7037!important}.close{position:absolute;right:12px;top:8px;border:0;background:none;font-size:24px}.error{color:#e91010}@media(max-width:760px){.page{padding:20px}.card{padding:20px}.title{gap:16px;align-items:flex-start}}
</style>
