<script setup lang="ts">
import { onMounted, ref } from 'vue'
import SitterPageShell from '../components/sitter/SitterPageShell.vue'
import { getPayout, updateBankAccount, type BankAccount, type Payout } from '../services/sitterPayout'
const payout=ref<Payout|null>(null), editing=ref(false), confirming=ref(false), busy=ref(false), error=ref('')
const bank=ref<BankAccount>({bankName:'',accountName:'',accountNumber:'',bankCode:'',bookBankImageUrl:''})
async function load(){try{payout.value=await getPayout();bank.value={...payout.value.bankAccount}}catch(e){error.value=e instanceof Error?e.message:'Unable to load payout'}}
function image(event:Event){const file=(event.target as HTMLInputElement).files?.[0];if(!file)return;if(!file.type.startsWith('image/')||file.size>5_000_000){error.value='Use an image no larger than 5 MB';return}const reader=new FileReader();reader.onload=()=>bank.value.bookBankImageUrl=String(reader.result);reader.readAsDataURL(file)}
async function save(){busy.value=true;try{bank.value=await updateBankAccount(bank.value);if(payout.value)payout.value.bankAccount={...bank.value};editing.value=false;confirming.value=false}catch(e){error.value=e instanceof Error?e.message:'Unable to update bank account'}finally{busy.value=false}}
onMounted(load)
</script>
<template><SitterPageShell><main class="page"><h1>Payout Option</h1><p v-if="error" class="error">{{error}}</p><template v-if="payout"><section v-if="!editing"><div class="summary"><article><small>Total Earning</small><strong>฿{{payout.totalEarning.toLocaleString()}}</strong></article><article><small>Bank Account</small><b>{{payout.bankAccount.bankName||'Not configured'}}</b><button @click="editing=true">Edit bank ›</button></article></div><div class="table"><table><thead><tr><th>Date</th><th>From</th><th>Transaction No.</th><th>Amount</th></tr></thead><tbody><tr v-for="t in payout.transactions" :key="t.bookingId"><td>{{new Date(t.completedAt).toLocaleDateString('en-GB')}}</td><td>{{t.ownerName}}</td><td>{{t.transactionNo||'—'}}</td><td class="amount">฿{{t.amount.toLocaleString()}}</td></tr><tr v-if="!payout.transactions.length"><td colspan="4">No payout transactions.</td></tr></tbody></table></div></section>
<form v-else class="form" @submit.prevent="confirming=true"><div class="form-head"><h2>Payout Option</h2><button type="submit">Update</button></div><label class="upload"><img v-if="bank.bookBankImageUrl" :src="bank.bookBankImageUrl" alt="Book bank preview"/><span v-else>Upload book bank image</span><input type="file" accept="image/*" @change="image"/></label><div class="fields"><label>Bank name<input v-model.trim="bank.bankName" required/></label><label>Account name<input v-model.trim="bank.accountName" required/></label><label>Account number<input v-model.trim="bank.accountNumber" inputmode="numeric" required/></label><label>Bank code<input v-model.trim="bank.bankCode"/></label></div></form></template>
<div v-if="confirming" class="overlay"><div class="modal"><h2>Payout Confirmation</h2><p>Are you sure to change your account?</p><button class="secondary" @click="confirming=false">Cancel</button><button :disabled="busy" @click="save">Yes, I'm sure</button></div></div></main></SitterPageShell></template>
<style scoped>
.page{padding:32px;background:#f7f8fc;min-height:calc(100svh - 78px)}.summary{display:grid;grid-template-columns:1fr 1fr;gap:16px}.summary article,.form,.table{background:#fff;border-radius:12px;padding:24px}.summary small,.summary strong{display:block}.summary strong{font-size:28px}.summary button,.form button,.modal button{float:right;border:0;border-radius:999px;background:#ff7037;color:#fff;padding:10px 18px}.table{margin-top:20px;overflow:auto}table{width:100%;border-collapse:collapse;min-width:650px}th{background:#111;color:#fff;text-align:left}th,td{padding:14px;border-bottom:1px solid #eef0f7}.amount{color:#22c07f}.form-head{display:flex;justify-content:space-between}.upload{display:grid;place-items:center;width:260px;height:190px;background:#eef0fb;margin:20px 0;cursor:pointer}.upload img{max-width:100%;max-height:100%}.upload input{display:none}.fields{display:grid;grid-template-columns:1fr 1fr;gap:18px}.fields label{display:grid;gap:7px}.fields input{padding:11px;border:1px solid #dde0ef;border-radius:6px}.overlay{position:fixed;inset:0;background:#0009;display:grid;place-items:center}.modal{background:#fff;border-radius:12px;padding:28px;text-align:center}.modal .secondary{float:none;background:#fff;color:#ff7037;border:1px solid #ff7037}.error{color:#e91010}@media(max-width:760px){.page{padding:20px}.summary,.fields{grid-template-columns:1fr}.upload{width:100%}}
</style>
